### ISSUE TITLE
README.md should contain more detailed description of the service

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/f8a-hpf-insights#39]
## Requirement needs to be done to met the F8A: Definition of Done

1. What's the purpose of the service?
1. How to use it (API description and/or link to swagger)
1. An example - given input and expected outputs

**Comment by tisnik** [comment]
@msrb @sivaavkd

**Comment by msrb** [comment]
@sara-02 's PR with the API documentation (work-in-progress) is here: https://github.com/fabric8-analytics/f8a-hpf-insights/pull/18

**Comment by sara-02** [comment]
@tisnik Swagger spec has been added https://github.com/fabric8-analytics/f8a-hpf-insights/blob/master/swagger/swagger.yaml.
