### ISSUE TITLE
Unit test criteria and REST API test to met F8A: Definition of Done

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/f8a-hpf-insights#40]
## The following criteria should be accomplished to met F8A: Definition of Done

- [x] unit test setup in the repository
- [x] unit test coverage ~ 50% (let's start with lover number)
- [x] the business logic needs to be covered
- [ ] REST API tests setup, in this repository or in the `fabric8-analytics-common` (ask me please)
- [x] all REST API endpoints covered by tests

**Comment by tisnik** [comment]
@msrb @sivaavkd

**Comment by sara-02** [comment]
@tisnik Ack.

**Comment by tisnik** [comment]
thanks @sara-02 Please don't hesitate to ask me for help with unit/rest-api tests.

**Comment by sara-02** [comment]
@tisnik I am closing this issue as the unit tests are covered. I will open two other issues for integration test and fix one broken test s respectively.

**Comment by sara-02** [comment]
Fixed in https://github.com/fabric8-analytics/f8a-hpf-insights/pull/43

**Comment by sara-02** [comment]
Currently we are at 92% coverage.

**Comment by sivaavkd** [comment]
@sara-02 I see that the issue is closed, but one task is still unchecked... also, can you please update the related planner item [330](https://openshift.io/openshiftio/Openshift_io/plan/detail/330) ? cc @tisnik @rootAvish @msrb

**Comment by sara-02** [comment]
@sivaavkd Updated.
