### ISSUE TITLE
Strange implementation of list-files method from local_data_store.py

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/f8a-hpf-insights#60]
The method `list-files` is different from the similar methods from other repositories:

1) the +1 in len() computation seems not to be correct (and it is not tested)

2) unused arguments that have sense for this method:

```
src/data_store/local_data_store.py
src/data_store/local_data_store.py:22: unused variable 'max_count' (100% confidence)
src/data_store/local_data_store.py:22: unused variable 'prefix' (100% confidence)
```

**Comment by lucky-suman** [comment]
The data store part has been moved to the Rudra library.
